GeoInfo:
    data:
        city: "jau"
        country: "bra"
        region: "sp"
    schemaVersion: 1
lol-audio:
    data:
        loginMusicEnabled: false
        masterVolume: 10
    schemaVersion: 5
lol-clash:
    data:
        simpleStateFlagIds:
        - "registration_open_tournament_141"
        - "registration_open_tournament_241"
        - "registration_open_tournament_881"
        - "registration_open_tournament_302"
        - "lock_in_open_tournament_261_phase_221"
        - "registration_open_tournament_1381"
        - "registration_open_tournament_261"
        - "lock_in_open_tournament_241_phase_201"
        - "registration_open_tournament_301"
        - "registration_open_tournament_882"
        - "registration_open_tournament_1441"
        - "lock_in_open_tournament_1381_phase_1341"
        - "registration_open_tournament_1382"
    schemaVersion: 1
lol-collection-champions:
    data:
        completeSetIdMap: null
        lastSessionId: "eyJraWQiOiJzMSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiN1dpTHplVW0tOTBjNlRuVWVydklnZyIsInN1YiI6ImE5YWI2YmY3LWY3NzYtNTNhOS04ZDdmLTZlNzZkZmM1Mzc0MiIsImNvdW50cnkiOiJpcmwiLCJwbGF5ZXJfcGxvY2FsZSI6ImVuLVVTIiwiYW1yIjpbImNvb2tpZSJdLCJpc3MiOiJodHRwczpcL1wvYXV0aC5yaW90Z2FtZXMuY29tIiwibG9sIjpbeyJjdWlkIjoyMDkxMDA5ODgsImNwaWQiOiJCUjEiLCJ1aWQiOjIwOTEwMDk4OCwidW5hbWUiOiJMZW9uYXJkb0Jhc3RpYW5pIiwicHRyaWQiOm51bGwsInBpZCI6IkJSMSIsInN0YXRlIjoiRU5BQkxFRCJ9XSwibG9jYWxlIjoicHRfQlIiLCJub25jZSI6IkN6MGNxelpibjVkM3ZqalFlRkpYMHciLCJhdWQiOiJsb2wiLCJhY3IiOiIwIiwicGxheWVyX2xvY2FsZSI6ImVuLVVTIiwiZXhwIjoxNTgwNzczODE1LCJpYXQiOjE1ODA2ODc0MTUsImFjY3QiOnsiZ2FtZV9uYW1lIjoiTGVvYmFzdGlhbmkiLCJ0YWdfbGluZSI6IkJSMSJ9LCJqdGkiOiJ5aUhXMVV6b2NBRSIsImxvZ2luX2NvdW50cnkiOiJicmEifQ.igQ8AYuwxoXwVOaUZY3YrdRFxdI1pjcI0tSgwELKrs3yw2r9pK8lKjwwjXANFZYKkz40xuUb9V6Q9xUJ7nnKXbWiKmJiPwyEip6LuDNEPhWDyrXcgQ8oP4BH-4TJo93i-C6cJOmHw3a_XywRC8pVe_rE8YueWKnu7ytnopG3Kes"
        lastVisitTime: 1577749302202
        visitedCollectibleList: []
    schemaVersion: 1
lol-collection-chromas:
    data:
        completeSetIdMap: null
        lastSessionId: "eyJraWQiOiJzMSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiQUd3d0w4aVRBLUFFSzJBUkpINk0xdyIsInN1YiI6ImE5YWI2YmY3LWY3NzYtNTNhOS04ZDdmLTZlNzZkZmM1Mzc0MiIsImNvdW50cnkiOiJpcmwiLCJwbGF5ZXJfcGxvY2FsZSI6ImVuLVVTIiwiYW1yIjpbImNvb2tpZSJdLCJpc3MiOiJodHRwczpcL1wvYXV0aC5yaW90Z2FtZXMuY29tIiwibG9sIjpbeyJjdWlkIjoyMDkxMDA5ODgsImNwaWQiOiJCUjEiLCJ1aWQiOjIwOTEwMDk4OCwidW5hbWUiOiJMZW9uYXJkb0Jhc3RpYW5pIiwicHRyaWQiOm51bGwsInBpZCI6IkJSMSIsInN0YXRlIjoiRU5BQkxFRCJ9XSwibG9jYWxlIjoicHRfQlIiLCJub25jZSI6IkgwZEJ6WGtzeVREbldGZTBoTGh5T2ciLCJhdWQiOiJsb2wiLCJhY3IiOiIwIiwicGxheWVyX2xvY2FsZSI6ImVuLVVTIiwiZXhwIjoxNTg1MzQ5MjMwLCJpYXQiOjE1ODUyNjI4MzAsImFjY3QiOnsiZ2FtZV9uYW1lIjoiTGVvYmFzdGlhbmkiLCJ0YWdfbGluZSI6IkJSMSJ9LCJqdGkiOiJDQURnS2d2c0pabyIsImxvZ2luX2NvdW50cnkiOiJicmEifQ.ViZzZLHv-UOJqO1qtg1trhXOvJ4Z5XjzDc-dzSX-5IPH4xFp8KKmqzwN4LQBuIzblvQNO_hHdAqENC1_ckbcn-QUKYrjs9LAd40bK3I8F-S_DCt2_wFdJKEoj-BxLkvZnayA791yw1tN8akDSCWznJhUN9AePbLtbHU1vqoYts8"
        lastVisitTime: 1585262855606
        visitedCollectibleList: []
    schemaVersion: 1
lol-collection-summoner-icons:
    data:
        completeSetIdMap: null
        lastSessionId: "eyJraWQiOiJzMSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiZVgySUVoUTRQY2Z4V25tRS1UVmlJUSIsInN1YiI6ImE5YWI2YmY3LWY3NzYtNTNhOS04ZDdmLTZlNzZkZmM1Mzc0MiIsImNvdW50cnkiOiJpcmwiLCJwbGF5ZXJfcGxvY2FsZSI6ImVuLVVTIiwiYW1yIjpbInBhc3N3b3JkIl0sImlzcyI6Imh0dHBzOlwvXC9hdXRoLnJpb3RnYW1lcy5jb20iLCJsb2wiOlt7ImN1aWQiOjIwOTEwMDk4OCwiY3BpZCI6IkJSMSIsInVpZCI6MjA5MTAwOTg4LCJ1bmFtZSI6Ikxlb25hcmRvQmFzdGlhbmkiLCJwdHJpZCI6bnVsbCwicGlkIjoiQlIxIiwic3RhdGUiOiJFTkFCTEVEIn1dLCJsb2NhbGUiOiJwdF9CUiIsIm5vbmNlIjoicllMNW8tOW1ra2Y3Q1ZETzZZX01kQSIsImF1ZCI6ImxvbCIsImFjciI6InVybjpyaW90OmJyb256ZSIsInBsYXllcl9sb2NhbGUiOiJlbi1VUyIsImV4cCI6MTU4NjgxMTAyMSwiaWF0IjoxNTg2NzI0NjIxLCJhY2N0Ijp7ImdhbWVfbmFtZSI6Ikxlb2Jhc3RpYW5pIiwidGFnX2xpbmUiOiJCUjEifSwianRpIjoiQllwWXdyQmZoMmciLCJsb2dpbl9jb3VudHJ5IjoiYnJhIn0.fgtlrLxK4pheGNo8_A45nE0rr1IbYrkvFYzaMVJu_3ftz-SjwYBkoYt8L2t2cWjme5JXSlmV53sbsv8IRzpRBCErdKTkUKvec6ttoPyb7VyD4I5D83Rt3jLW-UmqsALQsN6od9jFAGkwfRw0Hwpaectlq67xeenKrd2jKskxgik"
        lastVisitTime: 1586647711299
        visitedCollectibleList: []
    schemaVersion: 1
lol-collection-ward-skins:
    data:
        completeSetIdMap: null
        lastSessionId: "eyJraWQiOiJzMSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiZVgySUVoUTRQY2Z4V25tRS1UVmlJUSIsInN1YiI6ImE5YWI2YmY3LWY3NzYtNTNhOS04ZDdmLTZlNzZkZmM1Mzc0MiIsImNvdW50cnkiOiJpcmwiLCJwbGF5ZXJfcGxvY2FsZSI6ImVuLVVTIiwiYW1yIjpbInBhc3N3b3JkIl0sImlzcyI6Imh0dHBzOlwvXC9hdXRoLnJpb3RnYW1lcy5jb20iLCJsb2wiOlt7ImN1aWQiOjIwOTEwMDk4OCwiY3BpZCI6IkJSMSIsInVpZCI6MjA5MTAwOTg4LCJ1bmFtZSI6Ikxlb25hcmRvQmFzdGlhbmkiLCJwdHJpZCI6bnVsbCwicGlkIjoiQlIxIiwic3RhdGUiOiJFTkFCTEVEIn1dLCJsb2NhbGUiOiJwdF9CUiIsIm5vbmNlIjoicllMNW8tOW1ra2Y3Q1ZETzZZX01kQSIsImF1ZCI6ImxvbCIsImFjciI6InVybjpyaW90OmJyb256ZSIsInBsYXllcl9sb2NhbGUiOiJlbi1VUyIsImV4cCI6MTU4NjgxMTAyMSwiaWF0IjoxNTg2NzI0NjIxLCJhY2N0Ijp7ImdhbWVfbmFtZSI6Ikxlb2Jhc3RpYW5pIiwidGFnX2xpbmUiOiJCUjEifSwianRpIjoiQllwWXdyQmZoMmciLCJsb2dpbl9jb3VudHJ5IjoiYnJhIn0.fgtlrLxK4pheGNo8_A45nE0rr1IbYrkvFYzaMVJu_3ftz-SjwYBkoYt8L2t2cWjme5JXSlmV53sbsv8IRzpRBCErdKTkUKvec6ttoPyb7VyD4I5D83Rt3jLW-UmqsALQsN6od9jFAGkwfRw0Hwpaectlq67xeenKrd2jKskxgik"
        lastVisitTime: 1586724634323
        visitedCollectibleList: []
    schemaVersion: 1
lol-leagues:
    data:
        season-start-takeover:
            season: 9
    schemaVersion: 1
lol-parties:
    data:
        permanentHideAutofillModal: true
    schemaVersion: 1
lol-premade-voice:
    data:
        currentCaptureDeviceHandle: "{0.0.1.00000000}.{2843c0b7-d668-4a6a-ae8b-91feace20328}"
        inputVolume: 100
        vadSensitivity: 65
    schemaVersion: 1
lol-replays:
    data:
        dontShowEogUsageTip: true
    schemaVersion: 1
lol-skins-viewer:
    data:
        completeSetIdMap: null
        lastSessionId: "eyJraWQiOiJzMSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiZVgySUVoUTRQY2Z4V25tRS1UVmlJUSIsInN1YiI6ImE5YWI2YmY3LWY3NzYtNTNhOS04ZDdmLTZlNzZkZmM1Mzc0MiIsImNvdW50cnkiOiJpcmwiLCJwbGF5ZXJfcGxvY2FsZSI6ImVuLVVTIiwiYW1yIjpbInBhc3N3b3JkIl0sImlzcyI6Imh0dHBzOlwvXC9hdXRoLnJpb3RnYW1lcy5jb20iLCJsb2wiOlt7ImN1aWQiOjIwOTEwMDk4OCwiY3BpZCI6IkJSMSIsInVpZCI6MjA5MTAwOTg4LCJ1bmFtZSI6Ikxlb25hcmRvQmFzdGlhbmkiLCJwdHJpZCI6bnVsbCwicGlkIjoiQlIxIiwic3RhdGUiOiJFTkFCTEVEIn1dLCJsb2NhbGUiOiJwdF9CUiIsIm5vbmNlIjoicllMNW8tOW1ra2Y3Q1ZETzZZX01kQSIsImF1ZCI6ImxvbCIsImFjciI6InVybjpyaW90OmJyb256ZSIsInBsYXllcl9sb2NhbGUiOiJlbi1VUyIsImV4cCI6MTU4NjgxMTAyMSwiaWF0IjoxNTg2NzI0NjIxLCJhY2N0Ijp7ImdhbWVfbmFtZSI6Ikxlb2Jhc3RpYW5pIiwidGFnX2xpbmUiOiJCUjEifSwianRpIjoiQllwWXdyQmZoMmciLCJsb2dpbl9jb3VudHJ5IjoiYnJhIn0.fgtlrLxK4pheGNo8_A45nE0rr1IbYrkvFYzaMVJu_3ftz-SjwYBkoYt8L2t2cWjme5JXSlmV53sbsv8IRzpRBCErdKTkUKvec6ttoPyb7VyD4I5D83Rt3jLW-UmqsALQsN6od9jFAGkwfRw0Hwpaectlq67xeenKrd2jKskxgik"
        lastVisitTime: 1586122688064
        visitedSkinList: []
    schemaVersion: 1
lol-user-experience:
    data:
        lastKnownMachineSpec: 5
        potatoModeEnabled: true
        unloadUxInGameEnabled: false
    schemaVersion: 2
personalized-offers:
    data:
        lastViewedTimestamp: "2019-04-09T19:23:48.015Z"
    schemaVersion: 1
video:
    data:
        ZoomScale: 1
    schemaVersion: 1
